[package]
name = "adbcheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adb-rs = "0.1.3"
clap = { version = "4.0.29", features = ["derive"] }
